adding a picture of a princess, credit https://www.asciiart.eu/people…
TomMCauser/MNXB01-learn pull request #1
Opened 2020-10-15 15:26 UTC by floridop

Adding an asciiart of a princess, source in the commit message

2020-10-17 06:14 UTC, TomMCauser commented on README.md
> +           `--'   .'`<^>(-.'/-.L/-;\  bug  T_T "
Please fix the bug on this line.

2020-10-17 06:15 UTC, TomMCauser requested changes
There's currently a bug on line 36 - please resolve this and then send back.

2020-10-19 15:09 UTC, floridop commented on README.md
> +           `--'   .'`<^>(-.'/-.L/-;\  bug  T_T "
Good point :D! Unfortunately I can't since I believe that's the artist signature, and the webpage https://www.asciiart.eu/people/women says at the bottom:
>The ASCII art of this website has been created by many different artists and credit has been given where the artist is known.
>If you use ASCII artwork from here, please do not remove the artists name/initials if they are present.

Shall I then change picture to one with a least visible signature?

2020-10-20 08:16 UTC, TomMCauser commented on README.md
> +           `--'   .'`<^>(-.'/-.L/-;\  bug  T_T "
To be completely honest, I thought this was a "bug" that you put in "the code" for us to find and point out to you haha. But okay, no problem. I'll merge it.

2020-10-20 08:16 UTC, merged

2020-10-20 09:53 UTC, floridop commented
Thanks. grade updated